version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "eu-north-1"
    AWS_ACCOUNT_ID: "637423183951"
    ECR_REPOSITORY_NAME: "java"
    LAMBDA_FUNCTION_NAME: "java-gradle-fn"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update -y

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Checking if the ECR repository exists or needs to be created..."
      - |
        if ! aws ecr describe-repositories --repository-names $ECR_REPOSITORY_NAME --region $AWS_DEFAULT_REGION; then
          aws ecr create-repository --repository-name $ECR_REPOSITORY_NAME --region $AWS_DEFAULT_REGION
        fi

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ECR_REPOSITORY_NAME .
      - echo "Tagging the Docker image..."
      - docker tag $ECR_REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest
      - echo "Writing image definitions file..."
      - |
        printf '[{"name":"%s","imageUri":"%s"}]' $ECR_REPOSITORY_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY_NAME:latest > imagedefinitions.json
      - echo "Storing the image definitions file as an artifact..."

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml